Project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
<<<<<<< HEAD
=======
    path("tinymce/", include('tinymce.urls')),
    path("summernote/", include('django_summernote.urls')),
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21
    path("admin/", admin.site.urls),
    path("sfuanime/", include("sfuanime.urls"))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Project/mysite/sfuanime/urls.py
from django.urls import path


from . import views

app_name = 'sfuanime'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.posts, name='posts'),
    path('posts/tag/<str:tag>', views.post_tag, name='post_tag'),
<<<<<<< HEAD
    path('posts/date/<str:time>', views.post_month, name='post_month'),
    path('events/', views.events, name='events'),
    path('about/', views.about, name='about'),
    path('admins/', views.admins, name='admins'),
    path('postmaker/', views.postmaker, name='postmaker'),
    path('posts/<int:post_id>',views.post_index, name="post_index"),
=======
    path('posts/month/<str:month>', views.post_month, name='post_month'),
    path('events/', views.events, name='events'),
    path('about/', views.about, name='about'),
    path('admins/', views.admins, name='admins'),
    path('posts/<int:post_id>',views.post_index, name="post_index"),
    path('postmaker/',views.postmaker, name = "postmaker")
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21

]

Project/mysite/sfuanime/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField, ArrayField
from django.db import models

from django.utils import timezone
from tinymce.models import HTMLField
from tinymce.widgets import TinyMCE
from tinymce_4.fields import TinyMCEModelField





class Posts(models.Model):

    post_title  = models.CharField(max_length=200)
    post_content  = models.TextField(blank = True, null = True)
    post_date = models.DateTimeField()
    post_tag = ArrayField(models.CharField(max_length=30, null=True, blank=True), null=True)
    post_pic =  models.CharField(max_length=200)
<<<<<<< HEAD
=======

class MyModel(models.Model):
    content = HTMLField()
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21

class ModelFoo(models.Model):
    content = TinyMCEModelField('Foo Content')

# Create your models here.

Project/mysite/sfuanime/views.py
from django.shortcuts import render
from .models import Posts
from django.http import HttpResponse

def index(request):
    posts = Posts.objects.all()
    print("index")


    return render(request, 'sfuanime/index.html', {"posts":posts})



def posts(request):
    posts = Posts.objects.all()
    print("posts")



    return render(request, 'sfuanime/posts.html', {"posts":posts})



def events(request):
    return render(request, 'sfuanime/events.html')

def about(request):
    return render(request, 'sfuanime/about.html')

def admins(request):
    return render(request, 'sfuanime/admins.html')

def post_index(request, post_id):
    postid = Posts.objects.filter(id = post_id)
    next = post_id + 1
    prev = post_id - 1
    length = len(Posts.objects.all())

<<<<<<< HEAD
    return render(request, 'sfuanime/post_index.html',{"postid":postid,"next":next,"length":length, "prev":prev})


def post_tag(request,tag):
    taggy = tag
    posty = Posts.objects.all()

    tag_ans= posty.filter(post_tag__contains = [tag])

    return render(request, 'sfuanime/post_tag.html',{"tag":tag,"tag_ans":tag_ans})


def post_month(request,time):

    year = time[:4]
    month = time[4:]
    print(year)
    print(month)


    dep =Posts.objects.filter(post_date__year = year,post_date__month = month)

    return render(request, 'sfuanime/post_month.html',{"time":time,"dep":dep,"month":month,"year":year})
=======
    if length-1>post_id:
        return render(request, 'sfuanime/index.html', {"posts":posts})

    else:
        return render(request, 'sfuanime/post_index.html',{"postid":postid,"next":next,"length":length, "prev":prev})


def post_tag(request,tag):

    return render(request, 'sfuanime/post_tag.html')


def post_month(request,month):

    return render(request, 'sfuanime/post_month.html')
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21



def postmaker(request):

    return render(request, 'sfuanime/postmaker.html')






# Create your views here.

Project/mysite/sfuanime/templates/sfuanime/index.html
{% extends 'sfuanime/layout.html' %}
{% block content %}
{% load static %}


<!-- <img src ="{% static "img/lillie.jpg" %}" alt = "My Image"> -->
<!-- <div class="container" width="100%" style="position:relative;right:30px;top:30px;">
  <img src ="{% static "img/homecover.jpg" %}" alt = "My Image">
</div> -->




<div class="container" style="margin-top:100px;width:1000px;">

    <div class="row">


              <div class="container" style="width:333px;height:450px;background-color:#25BAF5;">
                    <h1 class="" style="color:white;margin-top:60px;font-size:36px;">Welcome to SFU Anime Beta</h1>

                      <p style="font-size:16px;color:white;margin-top:20px;"> This is a website about SFU Anime
                      Here you will find the latest news about our asdasdas events. Lorem ipsum asld alsdk alk dal dla
                      dlad ada dla sdla djenc jos x shhsj aksx akasdasd
			adasdsamd asd lasdl hxe xak.</p>

                      <button class="button button1" onClick="document.getElementById('middle').scrollIntoView();">MORE</button>


<<<<<<< HEAD
=======
                      <button class="button button1" onClick="document.getElementById('middle').scrollIntoView();">MORE</button>


>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21
              </div>


                      <div id="myCarousel" class="carousel slide" data-ride="carousel"
                       style="height:450px;width:667px;float:right;"  >
                         <!-- Indicators -->
                         <ol class="carousel-indicators">
                           <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                           <li data-target="#myCarousel" data-slide-to="1"></li>
                           <li data-target="#myCarousel" data-slide-to="2"></li>

                         </ol>

                         <!-- Wrapper for slides -->
                         <div class="carousel-inner">
                           <div class="item active ">
                             <img src="{% static "sfuanime/caro1.jpg" %}">
                           </div>

                           <div class="item">
                             <img src="{% static "sfuanime/caro2.jpg" %}" >
                           </div>
                           <div class="item">
                             <img src="{% static "sfuanime/caro3.jpg" %}" style="position:relative;bottom:80px;">
                           </div>

                         </div>

                         <!-- Left and right controls -->
                         <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                           <span class="glyphicon glyphicon-chevron-left"></span>
                           <span class="sr-only">Previous</span>
                         </a>
                         <a class="right carousel-control" href="#myCarousel" data-slide="next">
                           <span class="glyphicon glyphicon-chevron-right"></span>
                           <span class="sr-only">Next</span>
                         </a>

                         </div>

      </div>
    <div class="row" style="height:260px;">

      <div class="col-4" style="background-color:#6FE28D;text-align:center;">
            <i class="fas fa-calendar fa-10x" style="color:white;padding-top:50px;"></i>
              <a href="{% url 'sfuanime:events' %}">
            <h1 class="" style="color:white;padding-top:20px;">Events</h1></a>

        </div>

        <div class="col-4" style="background-color:#7F8296;text-align:center;">

          <i class="fas fa-picture-o fa-10x" style="color:white;padding-top:50px;"></i>
                <a href="{% url 'sfuanime:postmaker' %}">
                <h1 class="" style="color:white;padding-top:20px;">Gallery</h1></a>

          </div>

          <div class="col-4" style="background-color:#EB736A;text-align:center;">

            <i class="fas fa-address-card fa-10x" style="color:white;padding-top:50px;"></i>
                <a href="{% url 'sfuanime:admins' %}">
                  <h1 class="" style="color:white;padding-top:20px;">Membership</h1></a>

            </div>


      </div>


      <div class="row" style="height:260px;">

        <div class="col-4" style="background-color:#8F74A3;text-align:center;">
          <i class="fas fa-phone fa-10x" style="color:white;padding-top:50px;"></i>
                  <a href="{% url 'sfuanime:about' %}">
                <h1 class="" style="color:white;padding-top:20px;">Contact</h1></a>
          </div>

          <div class="col-4" style="background-color:#2CB66E;text-align:center;">
            <i class="fas fa-smile-o fa-10x" style="color:white;padding-top:50px;"></i>
                  <a href="{% url 'sfuanime:about' %}">
                  <h1 class="" style="color:white;padding-top:20px;">Mascot</h1></a>
            </div>

            <div class="col-4" style="background-color:#6374EC;text-align:center;">
              <i class="fas fa-handshake-o fa-10x" style="color:white;padding-top:50px;"></i>
                    <a href="{% url 'sfuanime:about' %}">
                  <h1 class="" style="color:white;padding-top:20px;">Sponsorship</h1>
            </div>
            </a>

        </div>


  <div class="row">
    <div class="col" style="margin-top:60px;">
      <h1 class="" style="margin-bottom:20px;font-size:20px;">Pinned Post</h1>

  <div id="middle" class="container" style="">
        <h1 class="text-primary">Welcome to SFU Anime Beta</h1>
    	     </div>
<<<<<<< HEAD

    <div class="box" style="background-color:#e8e8e8;padding:20px;">
      <p style="font-size:20px;"> This is a website about SFU Anime</p>
      <p style="font-size:20px;">Here you will find the latest news about our events</p>

      <p style="line-height: 2;font-size:14px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc. Hac habitasse platea dictumst vestibulum. Justo eget magna fermentum iaculis eu non diam. A scelerisque purus semper eget duis. Scelerisque fermentum dui faucibus in ornare. Mus mauris vitae ultricies leo integer malesuada. Eget felis eget nunc lobortis. Mattis molestie a iaculis at erat pellentesque. Nisl nisi scelerisque eu ultrices vitae.</p>
</div>




    </div>

    <div class="col-3" style="margin-top:100px;">

      <h1 class="text-dark">Important Events</h1>
      <br>
      <a href="{% url 'sfuanime:post_tag' "Tag1" %}"><p style="font-size:20px;"> Summer Festival</p></a>

      <a href="{% url 'sfuanime:post_tag' "Tag2" %}"><p style="font-size:20px;"> Weekly Screening Week 12</p></a>

      <a href="{% url 'sfuanime:post_tag' "Tag2" %}"><p style="font-size:20px;"> Icebreaker</p></a>
      <br>



      <h1 class="text-dark">Post by Month</h1>
      <br>
            <a href="{% url 'sfuanime:post_month' 201908 %}">  <p style="font-size:20px;"> August 2019 </p></a>
            <a href="{% url 'sfuanime:post_month' 201907 %}">  <p style="font-size:20px;"> July 2019 </p></a>
            <a href="{% url 'sfuanime:post_month' 201906 %}">  <p style="font-size:20px;"> June 2019 </p></a>
      <br>

      </div>


  </div>


  <h1 class="" style="margin-top:30px;font-size:20px;">Latest Post</h1>

<div class="row" style="margin-top:20px;margin-bottom:60px;">
  <div class="col-6" style="">




{% for p in posts %}
{% if p.id == 1 %}
<div class="card" style="">
  <div class="center-cropped" style="width:470px;overflow:hidden;">

      <img class="card-img-top" src="/static/{{ p.post_pic }}" >
  </div>


  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <a href="{% url 'sfuanime:post_index' p.id %}"><h1 class="text-primary">{{p.post_title}}</h1></a>
    <p style="font-size:18px;">{{p.post_date}}</p>
    <p style="font-size:18px;">{{p.post_content| truncatewords:10}}</p>
  <a href="{% url 'sfuanime:post_index' p.id %}"><h3>Check it out</h3></a>
  </div>
</div>
{% endif %}

{% endfor %}
=======

    <div class="box" style="background-color:#e8e8e8;padding:20px;">
      <p style="font-size:20px;"> This is a website about SFU Anime</p>
      <p style="font-size:20px;">Here you will find the latest news about our events</p>

      <p style="line-height: 2;font-size:14px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc. Hac habitasse platea dictumst vestibulum. Justo eget magna fermentum iaculis eu non diam. A scelerisque purus semper eget duis. Scelerisque fermentum dui faucibus in ornare. Mus mauris vitae ultricies leo integer malesuada. Eget felis eget nunc lobortis. Mattis molestie a iaculis at erat pellentesque. Nisl nisi scelerisque eu ultrices vitae.</p>
</div>




>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21
    </div>

  <div class="col-6" style="">

<<<<<<< HEAD
=======
      <h1 class="text-primary">Important Events</h1>
      <br>
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21



<<<<<<< HEAD


{% for p in posts %}
{% if p.id == 2 %}
<div class="card" style="">
  <div class="center-cropped" style="width:470px;overflow:hidden;">
      <img class="card-img-top" src="/static/{{ p.post_pic }}" >
  </div>

=======
      <p style="font-size:20px;"> Icebreaker</p>
      <br>
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21

  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <a href="{% url 'sfuanime:post_index' p.id %}"><h1 class="text-primary">{{p.post_title}}</h1></a>
    <p style="font-size:18px;">{{p.post_date}}</p>
    <p style="font-size:18px;">{{p.post_content| truncatewords:10}}</p>
  <a href="{% url 'sfuanime:post_index' p.id %}"><h3>Check it out</h3></a>
  </div>
</div>
{% endif %}

{% endfor %}


</div>






</div>






<div class="row" style="margin-top:20px;margin-bottom:60px;">
  <div class="col-6" style="">




{% for p in posts %}
{% if p.id == 3 %}
<div class="card" style="">
  <div class="center-cropped" style="width:470px;overflow:hidden;">

      <img class="card-img-top" src="/static/{{ p.post_pic }}" >
  </div>


<<<<<<< HEAD
=======
  <h1 class="" style="margin-top:30px;font-size:20px;">Latest Post</h1>

<div class="row" style="margin-top:20px;margin-bottom:60px;">
  <div class="col-6" style="">




{% for p in posts %}
{% if p.id == 1 %}
<div class="card" style="">
  <div class="center-cropped" style="width:470px;overflow:hidden;">

      <img class="card-img-top" src="/static/{{ p.post_pic }}" >
  </div>


>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <a href="{% url 'sfuanime:post_index' p.id %}"><h1 class="text-primary">{{p.post_title}}</h1></a>
    <p style="font-size:18px;">{{p.post_date}}</p>
    <p style="font-size:18px;">{{p.post_content| truncatewords:10}}</p>
  <a href="{% url 'sfuanime:post_index' p.id %}"><h3>Check it out</h3></a>
  </div>
</div>
{% endif %}

{% endfor %}
    </div>

  <div class="col-6" style="">






{% for p in posts %}
<<<<<<< HEAD
{% if p.id == 4 %}
=======
{% if p.id == 2 %}
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21
<div class="card" style="">
  <div class="center-cropped" style="width:470px;overflow:hidden;">
      <img class="card-img-top" src="/static/{{ p.post_pic }}" >
  </div>


  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <a href="{% url 'sfuanime:post_index' p.id %}"><h1 class="text-primary">{{p.post_title}}</h1></a>
    <p style="font-size:18px;">{{p.post_date}}</p>
    <p style="font-size:18px;">{{p.post_content| truncatewords:10}}</p>
  <a href="{% url 'sfuanime:post_index' p.id %}"><h3>Check it out</h3></a>
  </div>
</div>
{% endif %}

{% endfor %}


</div>






</div>







<<<<<<< HEAD
=======

>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21
    <div class="row" style="margin-top:60px;margin-bottom:60px;">

      <hr style="display:block;background-color:grey;height:1px;width:100%;">


        <p style="font-size:20px;"> This is a website about SFU Anime</p>
        <p style="font-size:20px;">Here you will find the latest news about our events</p>

        <p style="line-height: 2;font-size:14px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc. Hac habitasse platea dictumst vestibulum. Justo eget magna fermentum iaculis eu non diam. A scelerisque purus semper eget duis. Scelerisque fermentum dui faucibus in ornare. Mus mauris vitae ultricies leo integer malesuada. Eget felis eget nunc lobortis. Mattis molestie a iaculis at erat pellentesque. Nisl nisi scelerisque eu ultrices vitae.</p>



      </div>

</div>








<br>
<br>
<br>

</body>

{% endblock %}



</html>

Project/mysite/sfuanime/templates/sfuanime/post_index.html
{% extends 'sfuanime/layout.html' %}
{% block content %}
{% load static %}

<div class="container" style="margin-top:40px;margin-bottom:100px;">

  <h1 class="text-primary" style="font-size:30px;">Posts</h1>
    <a href="{% url 'sfuanime:index' %}"><button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" >
      Home</button></a>
        <p style="font-size:14px;display:inline-block;">></p>
           <a href="{% url 'sfuanime:posts' %}"><button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" >
          Post</button></a>
            <p style="font-size:14px;display:inline-block;">></p>
              {% for p in postid %}
            <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" >
          {{p.post_title}}</button>
            {% endfor %}


      <div class="row">

<<<<<<< HEAD
        <div class="col-9" style="">
=======
        <div class="col" style="">
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21

                  {% for p in postid %}

                  <div class="container" style="margin-top:80px;">




                  <h1 class="text-primary" style="font-size:40px;">{{p.post_title}}</h1>


                  <p style="font-size:20px;margin-top:20px;">Published Date: {{p.post_date}}</p>

                  <div class="center-cropped2" style="margin-top:20px;">
                      <img src="/static/{{ p.post_pic }}" >
                  </div>


                  <p style="font-size:30px;margin-top:60px;">{{p.post_content}}</p>
                  {% for pp in p.post_tag %}
                      <p style="font-size:20px;display:inline-block;padding-right:20px;margin-top:20px;"> {{pp}} </p>

                  {% endfor %}



                  </div>

                  {% endfor %}




        </div>

<<<<<<< HEAD
        <div class="col-3" style="">

          <h1 class="text-primary">Post by Month</h1>
          <br>
                <a href="{% url 'sfuanime:post_month' 201908 %}">  <p style="font-size:20px;"> August 2019 </p></a>
                <a href="{% url 'sfuanime:post_month' 201907 %}">  <p style="font-size:20px;"> July 2019 </p></a>
                <a href="{% url 'sfuanime:post_month' 201906 %}">  <p style="font-size:20px;"> June 2019 </p></a>
          <br>


        </div>

=======
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21
      </div>
      {% for p in postid %}

        <div class="row">
          <div class="container" style="margin-top:80px;">
            {%  if p.id == 1  %}
            <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" disabled="disabled">< Prev Post</button>
            {% else %}
            <a href="{% url 'sfuanime:post_index' prev %}">  <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" > < Prev Post </button></a>

            {% endif %}

          {%  if next > length %}
           <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;float:right;" disabled="disabled">Next Post ></button>
          {% else %}
           <a href="{% url 'sfuanime:post_index' next %}"> <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;float:right;">Next Post ></button></a>
          {% endif %}
          </div>

        </div>

      {% endfor %}


</div>







</body>




{% endblock %}



</html>

Project/mysite/sfuanime/templates/sfuanime/post_month.html
{% extends 'sfuanime/layout.html' %}
{% block content %}
{% load static %}

<div class="container" style="margin-top:40px;margin-bottom:100px;">

  <h1 class="text-primary" style="font-size:30px;">Posts</h1>
    <a href="{% url 'sfuanime:index' %}"><button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" >
      Home</button></a>
        <p style="font-size:14px;display:inline-block;">></p>
           <a href="{% url 'sfuanime:posts' %}"><button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" >
          Post</button></a>
            <p style="font-size:14px;display:inline-block;">></p>
<<<<<<< HEAD

            <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" >
          {{month}} {{year}}</button>



            <div class="row">

              <div class="col" style="">


                                {% for t in dep %}

                                <div class="card" style="margin-top:20px;">
                                  <div class="center-cropped">
                                      <img class="card-img-top" src="/static/{{ t.post_pic }}" >
                                  </div>


                                  <div class="card-body">
                                    <h5 class="card-title">Card title</h5>
                                    <a href="{% url 'sfuanime:post_index' t.id %}"><h1 class="text-primary">{{t.post_title}}</h1></a>
                                    <p style="font-size:18px;">{{t.post_date}}</p>
                                    <p style="font-size:18px;">{{t.post_content| truncatewords:100}}</p>



                                  </div>
                                </div>

                                {% endfor %}




              </div>

            </div>
=======
              {% for p in postid %}
            <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" >
          {{p.post_title}}</button>
            {% endfor %}


      <div class="row">

        <div class="col" style="">

                  {% for p in postid %}

                  <div class="container" style="margin-top:80px;">




                  <h1 class="text-primary" style="font-size:40px;">{{p.post_title}}</h1>


                  <p style="font-size:20px;margin-top:20px;">Published Date: {{p.post_date}}</p>

                  <div class="center-cropped2" style="margin-top:20px;">
                      <img src="/static/{{ p.post_pic }}" >
                  </div>


                  <p style="font-size:30px;margin-top:60px;">{{p.post_content}}</p>
                  {% for pp in p.post_tag %}
                      <p style="font-size:20px;display:inline-block;padding-right:20px;margin-top:20px;"> {{pp}} </p>

                  {% endfor %}



                  </div>

                  {% endfor %}




        </div>

      </div>
>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21
      {% for p in postid %}

        <div class="row">
          <div class="container" style="margin-top:80px;">
            {%  if p.id == 1  %}
            <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" disabled="disabled">< Prev Post</button>
            {% else %}
            <a href="{% url 'sfuanime:post_index' prev %}">  <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" > < Prev Post </button></a>

            {% endif %}

          {%  if next > length %}
           <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;float:right;" disabled="disabled">Next Post ></button>
          {% else %}
           <a href="{% url 'sfuanime:post_index' next %}"> <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;float:right;">Next Post ></button></a>
          {% endif %}
          </div>

        </div>

      {% endfor %}


</div>







</body>




{% endblock %}



</html>

Project/mysite/sfuanime/templates/sfuanime/posts.html
{% extends 'sfuanime/layout.html' %}
{% block content %}
{% load static %}

<div class="container" style="margin-top:100px;margin-bottom:100px;">


    <h1 class="text-primary" style="font-size:30px;">Posts</h1>
      <a href="{% url 'sfuanime:index' %}"><button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" >
        Home</button></a>
          <p style="font-size:14px;display:inline-block;">></p>
           <button type="button" class="btn btn-primary" style="font-size:20px;display:inline-block;" >
            Post</button></a>


      <div class="row">
        <div class="col" style="">


                {% for p in posts %}

                <div class="card" style="margin-top:20px;">
                  <div class="center-cropped">
                      <img class="card-img-top" src="/static/{{ p.post_pic }}" >
                  </div>


                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <a href="{% url 'sfuanime:post_index' p.id %}"><h1 class="text-primary">{{p.post_title}}</h1></a>
                    <p style="font-size:18px;">{{p.post_date}}</p>
                    <p style="font-size:18px;">{{p.post_content| truncatewords:100}}</p>

                  {% for pp in p.post_tag %}
                    <a href="{% url 'sfuanime:post_tag' pp %}">  <p style="font-size:20px;display:inline-block;padding-right:20px;"> {{pp}} </p></a>
                  {% endfor %}

                  </div>
                </div>




                {% endfor %}
<<<<<<< HEAD

                  </div>




        <div class="col-3" style="">

          <h1 class="text-dark">Post by Month</h1>
          <br>
                <a href="{% url 'sfuanime:post_month' 201908 %}">  <p style="font-size:20px;"> August 2019 </p></a>
                <a href="{% url 'sfuanime:post_month' 201907 %}">  <p style="font-size:20px;"> July 2019 </p></a>
                <a href="{% url 'sfuanime:post_month' 201906 %}">  <p style="font-size:20px;"> June 2019 </p></a>
          <br>


          <h1 class="text-dark">Important Events</h1>
          <br>
          <a href="{% url 'sfuanime:post_tag' "Tag1" %}"><p style="font-size:20px;"> Summer Festival</p></a>

          <a href="{% url 'sfuanime:post_tag' "Tag2" %}"><p style="font-size:20px;"> Weekly Screening Week 12</p></a>

          <a href="{% url 'sfuanime:post_tag' "Tag2" %}"><p style="font-size:20px;"> Icebreaker</p></a>
          <br>



        </div>



      </div>




</div>

=======

                  </div>




        <div class="col-3" style="">

          <h1 class="text-primary">Post by Month</h1>
          <br>
                <p style="font-size:20px;"> August 2019 </p>
                <p style="font-size:20px;"> July 2019 </p>
                <p style="font-size:20px;"> June 2019 </p>
          <br>

          <h1 class="text-primary">Tag</h1>
          <br>
                <p style="font-size:20px;"> Summer Festival </p>
                <p style="font-size:20px;"> Weekly Screenings </p>
                <p style="font-size:20px;"> Club Days </p>
          <br>


        </div>



      </div>




</div>

>>>>>>> 73f157eac73a6ce53f5775d16b5e182438dd4a21






</body>




{% endblock %}



</html>